# replace clock_bridge
- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  
# Eye-to-hand topics
- topic_name: "/eye_to_hand_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- topic_name: "/eye_to_hand_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS


# Eye-in-hand topics
- topic_name: "/eye_in_hand_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- topic_name: "/eye_in_hand_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS


# RGBD topics for eye-in-hand camera
- ros_topic_name: "/camera/color/image_raw"
  gz_topic_name: "/world/empty/model/ur_handeye_workcell/link/wrist_3_link/sensor/eye_in_hand_camera_rgbd_sensor/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  ros_frame_id: "eye_in_hand_camera_color_optical_frame"

- ros_topic_name: "/camera/depth/image_raw"
  gz_topic_name: "/world/empty/model/ur_handeye_workcell/link/wrist_3_link/sensor/eye_in_hand_camera_rgbd_sensor/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  ros_frame_id: "eye_in_hand_camera_color_optical_frame"

- ros_topic_name: "/camera/color/camera_info"
  gz_topic_name: "/world/empty/model/ur_handeye_workcell/link/wrist_3_link/sensor/eye_in_hand_camera_rgbd_sensor/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  ros_frame_id: "eye_in_hand_camera_color_optical_frame"

- ros_topic_name: "/camera/points"
  gz_topic_name: "/world/empty/model/ur_handeye_workcell/link/wrist_3_link/sensor/eye_in_hand_camera_rgbd_sensor/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  ros_frame_id: "eye_in_hand_camera_color_optical_frame"